# Generated by Django 5.2.10 on 2026-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True)),
                ('content_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga'), ('manhwa', 'Manhwa')], max_length=10)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
